on: push
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Install dependencies
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 📂 Install npm dependencies
      run: npm install
      working-directory: "PARTIE FRONT END/Quai Antique Dev/"

    - name: 📂 Deploy via SFTP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ssh-quai-antique-restaurante.alwaysdata.net
        username: quai-antique-restaurante
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "PARTIE FRONT END/Quai Antique Dev/*"
        target: /www/
        strip_components: 3
